"""Gates for the documentation site (PLAN.md, M13.5 and M13.6).

Five laws over the pages themselves. All of them are pure text or AST, all of
them always run:

1. the API reference lists every name in `__all__`;
2. every design note carries at least one `>>>` block — the guard against the
   silent-zero hole, see below;
3. every tutorial page's `{code-cell}` blocks execute, in order, in one shared
   namespace (M13.6);
4. no U+2014 in documentation prose (M13.6). Two commits established this by
   hand and nothing protected it. Source-level, not rendered: the rendered
   count was the right measure for auditing inherited docstrings, but the
   enforceable law is over what the author writes.

That the site *builds* clean under `-W` with `nitpicky = True` is a commit gate
of its own, run as `sphinx-build` directly (CLAUDE.md). It used to live here as
a sixth law wrapped in a subprocess and hidden behind a `DESIGNSPACE_DOCS_BUILD`
environment variable, which meant a gate nobody ran outside one CI job.

Law 3 is the counterpart of law 2 for pages that carry no `>>>`. A tutorial
page's outputs are generated by myst-nb at build time rather than written down,
which is the whole point: nobody transcribes a 500-draw report or a DataFrame by
hand. The cost is that nothing compares an output against an expectation, so the
pages carry `assert` statements for the claims their prose makes, and this law
runs them.

It duplicates the build's own execution deliberately, and stays worth its keep
now that the build always runs: it costs ~2s against the build's ~17s, and it
reports the page and cell number that raised rather than a Sphinx warning. It
also asserts the `file_format: mystnb` front matter, without which myst-nb
renders the cells and never executes them. Divergence between the two is not a
real risk, since both execute the same cells in the same order.

Law 2 exists because a doctest gate that collects nothing reports green. M13
lost all 83 doctests in the builder package that way, back when it was named
`src/designspace/build/` and pytest's default `norecursedirs` skipped it as
build output, and `pytest -q` stayed green throughout. The doctest gate walks
`docs/` for the same reason; this asserts the pages actually carry the tests
that command is there to run.
"""

from __future__ import annotations

import re
import warnings
from pathlib import Path

import pytest

import designspace as ds

_ROOT = Path(__file__).resolve().parent.parent
_DOCS = _ROOT / "docs"
_EXAMPLES = _ROOT / "examples"
_DESIGN_NOTES = sorted((_DOCS / "design-notes").glob("*.md"))
_TUTORIALS = sorted(p for p in (_DOCS / "tutorials").glob("*.md") if p.stem != "index")
_EXAMPLE_SCRIPTS = sorted(_EXAMPLES.glob("*.py"))
# `_build` is gitignored output, not authored prose, and `conf.py` excludes it
# from the build for the same reason.
_DOC_SOURCES = sorted(p for p in _DOCS.rglob("*.md") if "_build" not in p.parts)

_EM_DASH = "—"

# ```{code-cell}\n:tags: [...]\n<source>\n``` — myst-nb's executable block.
# Anchored at the fence so a mention in prose cannot match.
_CODE_CELL = re.compile(
    r"^```\{code-cell\}[^\n]*\n(?P<body>.*?)^```",
    re.MULTILINE | re.DOTALL,
)
# Directive options lead the body and are not Python.
_CELL_OPTION = re.compile(r"\A(?:^:[a-z-]+:.*$\n)+", re.MULTILINE)


def test_reference_lists_every_export() -> None:
    """Every exported name appears in the API reference.

    Without this the reference silently stops covering the surface the moment
    a milestone exports something new — which is exactly what M13's export
    closure did (79 names to 91) and M13.5 did again (91 to 96).
    """
    text = (_DOCS / "reference.md").read_text()
    missing = [
        name for name in ds.__all__ if name != "__version__" and f"designspace.{name}\n" not in text
    ]
    assert not missing, (
        f"{len(missing)} exported names are absent from docs/reference.md: "
        f"{', '.join(sorted(missing))}"
    )


def test_design_notes_exist() -> None:
    """The design-notes directory is not empty and is reachable from its index."""
    assert _DESIGN_NOTES, "docs/design-notes/ has no pages"
    index = (_DOCS / "design-notes" / "index.md").read_text()
    orphans = [p.stem for p in _DESIGN_NOTES if p.stem != "index" and p.stem not in index]
    assert not orphans, f"design notes missing from the toctree: {', '.join(orphans)}"


@pytest.mark.parametrize("page", _DESIGN_NOTES, ids=[p.stem for p in _DESIGN_NOTES])
def test_design_note_carries_doctests(page: Path) -> None:
    """Every design note except the index carries a runnable example.

    `--doctest-glob=*.md` runs them; this asserts there is something to run,
    so a page cannot quietly become prose-only while the gate reports green.
    """
    if page.stem == "index":
        pytest.skip("the index is a table of contents, not a design note")
    assert ">>>" in page.read_text(), (
        f"{page.name} carries no `>>>` example. A design note argues a "
        f"trade-off, and the argument is grounded in code that runs; see "
        f"PLAN.md M13.5."
    )


def test_tutorial_pages_exist() -> None:
    """The tutorial directory is not empty and is reachable from its index."""
    assert _TUTORIALS, "docs/tutorials/ has no pages"
    index = (_DOCS / "tutorials" / "index.md").read_text()
    orphans = [p.stem for p in _TUTORIALS if p.stem not in index]
    assert not orphans, f"tutorial pages missing from the toctree: {', '.join(orphans)}"


@pytest.mark.parametrize("page", _TUTORIALS, ids=[p.stem for p in _TUTORIALS])
def test_tutorial_page_executes(page: Path) -> None:
    """Every `{code-cell}` on a tutorial page runs, in order, in one namespace.

    A tutorial's outputs are generated by myst-nb rather than written down, so
    nothing compares them against an expectation. What the pages assert instead
    is stated inline: cells carry `assert` statements for the claims their prose
    makes, and this law runs them on a plain `pytest -q`, in ~2s, naming the
    cell that raised. The site build runs the same cells for real.

    A page must open with `file_format: mystnb` front matter, or myst-nb parses
    it as ordinary markdown and silently renders the cells without ever running
    them.
    """
    text = page.read_text()
    assert text.startswith("---\nfile_format: mystnb\n---\n"), (
        f"{page.name} lacks `file_format: mystnb` front matter, so myst-nb will "
        f"render its code cells without executing them."
    )

    cells = [_CELL_OPTION.sub("", m.group("body")) for m in _CODE_CELL.finditer(text)]
    assert cells, f"{page.name} carries no `{{code-cell}}`; tutorial pages are executable"

    namespace: dict[str, object] = {}
    for number, source in enumerate(cells, start=1):
        try:
            # Pages demonstrate best-effort operations that warn by design.
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                exec(compile(source, f"{page.name}:cell{number}", "exec"), namespace)
        except Exception as exc:
            pytest.fail(
                f"{page.name} cell {number} raised {type(exc).__name__}: {exc}\n"
                f"--- cell source ---\n{source}"
            )


@pytest.mark.parametrize(
    "path",
    [*_DOC_SOURCES, *_EXAMPLE_SCRIPTS, _EXAMPLES / "README.md"],
    ids=lambda p: str(p.relative_to(_ROOT)),
)
def test_no_em_dash_in_documentation_prose(path: Path) -> None:
    """Documentation prose carries no U+2014.

    Objective, so it is gated. Register is not: second-person counts and
    antithesis counts are editorial judgment, and a threshold test over them
    would be brittle and would invite gaming.
    """
    lines = [
        f"  line {i}: {line.strip()}"
        for i, line in enumerate(path.read_text().splitlines(), start=1)
        if _EM_DASH in line
    ]
    assert not lines, f"{path.relative_to(_ROOT)} contains U+2014:\n" + "\n".join(lines)
