"""Gates for the documentation site and for authored prose.

Two groups of law, all of them pure text, all of them always run.

Coverage of the site:

1. the API reference lists every name in `__all__`;
2. every design note carries at least one `>>>` block, so a page cannot become
   prose-only while the doctest gate, which reports green on collecting
   nothing, stays green;
3. every tutorial page's `{code-cell}` blocks execute, in order, in one shared
   namespace. A tutorial's outputs are generated by myst-nb rather than written
   down, so nothing compares them against an expectation; the pages carry
   `assert` statements for the claims their prose makes, and this runs them in
   ~2s on a plain `pytest -q`, naming the cell that raised. It also asserts the
   `file_format: mystnb` front matter, without which myst-nb renders the cells
   and never executes them.

The prose standard in `CLAUDE.md`, over the trees `_PROSE_SOURCES` names:

4. no U+2014;
5. no decision-ledger entry cited by number outside `DECISIONS.md`;
6. no milestone number outside `PLAN.md` and `PROGRESS.md`;
7. every test module the spec's conformance laws name exists, and every entry
   in the spec's contents list points at one of its headings.

These four are the mechanically checkable part of that standard. Register is
not gated: second-person counts and antithesis counts are editorial judgment,
and a threshold test over them would be brittle and would invite gaming.

That the site *builds* clean under `-W` with `nitpicky = True` is a commit gate
of its own, run as `sphinx-build` directly (CLAUDE.md).
"""

from __future__ import annotations

import re
import warnings
from pathlib import Path

import pytest

import designspace as ds

_ROOT = Path(__file__).resolve().parent.parent
_DOCS = _ROOT / "docs"
_EXAMPLES = _ROOT / "examples"
_DESIGN_NOTES = sorted((_DOCS / "design-notes").glob("*.md"))
_TUTORIALS = sorted(p for p in (_DOCS / "tutorials").glob("*.md") if p.stem != "index")
_EXAMPLE_SCRIPTS = sorted(_EXAMPLES.glob("*.py"))
# `_build` is gitignored output, not authored prose, and `conf.py` excludes it
# from the build for the same reason.
_DOC_SOURCES = sorted(p for p in _DOCS.rglob("*.md") if "_build" not in p.parts)

_SPEC = _ROOT / "API.md"
_ROOT_MARKDOWN = [
    _SPEC,
    _ROOT / "PLAN.md",
    _ROOT / "PROGRESS.md",
    _ROOT / "DECISIONS.md",
    _ROOT / "CLAUDE.md",
    _ROOT / "README.md",
]

# The trees the prose laws cover. `src/` and `tests/` join this list at M13.8;
# until then they carry the register the standard replaced.
_PROSE_SOURCES = [*_DOC_SOURCES, *_EXAMPLE_SCRIPTS, _EXAMPLES / "README.md", *_ROOT_MARKDOWN]

_EM_DASH = "—"
# A decision-ledger entry number. Legal in DECISIONS.md, nowhere else.
_DECISION_CITATION = re.compile(r"\bD-\d+\b")
# A milestone number. Legal in PLAN.md and PROGRESS.md, whose subject it is.
_MILESTONE = re.compile(r"\bM\d+(?:\.\d+)?\b")
# A `tests/...py` path cited in the spec's "Enforced by" column.
_TEST_MODULE = re.compile(r"`(tests/[\w/]+\.py)`")
# A contents entry pointing at a heading of the same document.
_ANCHOR_LINK = re.compile(r"\]\(#([a-z0-9-]+)\)")
_HEADING = re.compile(r"^#{2,3} (.*)$", re.MULTILINE)

# ```{code-cell}\n:tags: [...]\n<source>\n``` is myst-nb's executable block.
# Anchored at the fence so a mention in prose cannot match.
_CODE_CELL = re.compile(
    r"^```\{code-cell\}[^\n]*\n(?P<body>.*?)^```",
    re.MULTILINE | re.DOTALL,
)
# Directive options lead the body and are not Python.
_CELL_OPTION = re.compile(r"\A(?:^:[a-z-]+:.*$\n)+", re.MULTILINE)


def _slug(heading: str) -> str:
    """The anchor a markdown renderer derives from a heading."""
    return re.sub(r"\s+", "-", re.sub(r"[^\w\s-]", "", heading.strip().lower())).strip("-")


def _cite_lines(path: Path, pattern: re.Pattern[str]) -> list[str]:
    return [
        f"  line {i}: {line.strip()}"
        for i, line in enumerate(path.read_text().splitlines(), start=1)
        if pattern.search(line)
    ]


def test_reference_lists_every_export() -> None:
    """Every exported name appears in the API reference.

    Without this the reference silently stops covering the surface the moment
    a milestone exports something new — which is exactly what M13's export
    closure did (79 names to 91) and M13.5 did again (91 to 96).
    """
    text = (_DOCS / "reference.md").read_text()
    missing = [
        name for name in ds.__all__ if name != "__version__" and f"designspace.{name}\n" not in text
    ]
    assert not missing, (
        f"{len(missing)} exported names are absent from docs/reference.md: "
        f"{', '.join(sorted(missing))}"
    )


def test_design_notes_exist() -> None:
    """The design-notes directory is not empty and is reachable from its index."""
    assert _DESIGN_NOTES, "docs/design-notes/ has no pages"
    index = (_DOCS / "design-notes" / "index.md").read_text()
    orphans = [p.stem for p in _DESIGN_NOTES if p.stem != "index" and p.stem not in index]
    assert not orphans, f"design notes missing from the toctree: {', '.join(orphans)}"


@pytest.mark.parametrize("page", _DESIGN_NOTES, ids=[p.stem for p in _DESIGN_NOTES])
def test_design_note_carries_doctests(page: Path) -> None:
    """Every design note except the index carries a runnable example.

    `--doctest-glob=*.md` runs them; this asserts there is something to run,
    so a page cannot quietly become prose-only while the gate reports green.
    """
    if page.stem == "index":
        pytest.skip("the index is a table of contents, not a design note")
    assert ">>>" in page.read_text(), (
        f"{page.name} carries no `>>>` example. A design note argues a "
        f"trade-off, and the argument is grounded in code that runs; see "
        f"PLAN.md M13.5."
    )


def test_tutorial_pages_exist() -> None:
    """The tutorial directory is not empty and is reachable from its index."""
    assert _TUTORIALS, "docs/tutorials/ has no pages"
    index = (_DOCS / "tutorials" / "index.md").read_text()
    orphans = [p.stem for p in _TUTORIALS if p.stem not in index]
    assert not orphans, f"tutorial pages missing from the toctree: {', '.join(orphans)}"


@pytest.mark.parametrize("page", _TUTORIALS, ids=[p.stem for p in _TUTORIALS])
def test_tutorial_page_executes(page: Path) -> None:
    """Every `{code-cell}` on a tutorial page runs, in order, in one namespace.

    A tutorial's outputs are generated by myst-nb rather than written down, so
    nothing compares them against an expectation. What the pages assert instead
    is stated inline: cells carry `assert` statements for the claims their prose
    makes, and this law runs them on a plain `pytest -q`, in ~2s, naming the
    cell that raised. The site build runs the same cells for real.

    A page must open with `file_format: mystnb` front matter, or myst-nb parses
    it as ordinary markdown and silently renders the cells without ever running
    them.
    """
    text = page.read_text()
    assert text.startswith("---\nfile_format: mystnb\n---\n"), (
        f"{page.name} lacks `file_format: mystnb` front matter, so myst-nb will "
        f"render its code cells without executing them."
    )

    cells = [_CELL_OPTION.sub("", m.group("body")) for m in _CODE_CELL.finditer(text)]
    assert cells, f"{page.name} carries no `{{code-cell}}`; tutorial pages are executable"

    namespace: dict[str, object] = {}
    for number, source in enumerate(cells, start=1):
        try:
            # Pages demonstrate best-effort operations that warn by design.
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                exec(compile(source, f"{page.name}:cell{number}", "exec"), namespace)
        except Exception as exc:
            pytest.fail(
                f"{page.name} cell {number} raised {type(exc).__name__}: {exc}\n"
                f"--- cell source ---\n{source}"
            )


@pytest.mark.parametrize("path", _PROSE_SOURCES, ids=lambda p: str(p.relative_to(_ROOT)))
def test_no_em_dash_in_documentation_prose(path: Path) -> None:
    """Authored prose carries no U+2014.

    Objective, so it is gated. Register is not: second-person counts and
    antithesis counts are editorial judgment, and a threshold test over them
    would be brittle and would invite gaming.
    """
    lines = [
        f"  line {i}: {line.strip()}"
        for i, line in enumerate(path.read_text().splitlines(), start=1)
        if _EM_DASH in line
    ]
    assert not lines, f"{path.relative_to(_ROOT)} contains U+2014:\n" + "\n".join(lines)


@pytest.mark.parametrize(
    "path",
    [p for p in _PROSE_SOURCES if p.name != "DECISIONS.md"],
    ids=lambda p: str(p.relative_to(_ROOT)),
)
def test_no_decision_citations_outside_the_ledger(path: Path) -> None:
    """Only `DECISIONS.md` names a decision entry by number.

    An entry is deleted once its answer is folded into `API.md`, so a `D-NN`
    written anywhere else resolves to nothing a reader can open. State the
    reason in words instead.
    """
    lines = _cite_lines(path, _DECISION_CITATION)
    assert not lines, f"{path.relative_to(_ROOT)} cites a decision entry by number:\n" + "\n".join(
        lines
    )


@pytest.mark.parametrize(
    "path",
    [_SPEC, *_DOC_SOURCES, *_EXAMPLE_SCRIPTS, _EXAMPLES / "README.md"],
    ids=lambda p: str(p.relative_to(_ROOT)),
)
def test_no_milestone_references_in_the_specification(path: Path) -> None:
    """Milestone numbers appear only in `PLAN.md` and `PROGRESS.md`.

    Those two documents have milestones as their subject. Everywhere else a
    milestone number dates the text against a schedule the reader cannot see.
    """
    lines = _cite_lines(path, _MILESTONE)
    assert not lines, f"{path.relative_to(_ROOT)} references a milestone:\n" + "\n".join(lines)


def test_spec_cites_test_modules_that_exist() -> None:
    """Every test module named in the spec's conformance laws exists."""
    cited = sorted(set(_TEST_MODULE.findall(_SPEC.read_text())))
    assert cited, "API.md's conformance laws name no test module"
    missing = [name for name in cited if not (_ROOT / name).is_file()]
    assert not missing, f"API.md names test modules that do not exist: {', '.join(missing)}"


def test_spec_contents_links_resolve() -> None:
    """Every entry in the spec's contents list points at one of its headings."""
    text = _SPEC.read_text()
    headings = {_slug(h) for h in _HEADING.findall(text)}
    broken = sorted({a for a in _ANCHOR_LINK.findall(text) if a not in headings})
    assert not broken, f"API.md contents entries point at no heading: {', '.join(broken)}"
