"""Gates for the documentation site and for authored prose.

Two groups of law, all of them pure text, all of them always run.

Coverage of the site:

1. the API reference lists every name in `__all__`;
2. every design note carries at least one `>>>` block, so a page cannot become
   prose-only while the doctest gate, which reports green on collecting
   nothing, stays green;
3. every tutorial page's `{code-cell}` blocks execute, in order, in one shared
   namespace. A tutorial's outputs are generated by myst-nb rather than written
   down, so nothing compares them against an expectation; the pages carry
   `assert` statements for the claims their prose makes, and this runs them in
   about two seconds on a plain `pytest -q`, naming the cell that raised. It
   also asserts the `file_format: mystnb` front matter, without which myst-nb
   renders the cells and never executes them.

The prose standard in `CLAUDE.md`, over the trees `_PROSE_SOURCES` names:

4. no U+2014;
5. no decision-ledger entry cited by number outside `DECISIONS.md`;
6. no milestone number outside `PLAN.md` and `PROGRESS.md`;
7. every test module the spec's conformance laws name exists, and every entry
   in the spec's contents list points at one of its headings;
8. every `API.md` section a docstring or comment cites is a heading of
   `API.md`, including its bold run-in form;
9. every conformance law names itself in the module the spec's *Enforced by*
   column assigns it, so the column reads in both directions.

These are the mechanically checkable part of that standard. Register is not
gated: second-person counts and antithesis counts are editorial judgment, and a
threshold test over them would be brittle and would invite gaming.

That the site builds clean under `-W` with `nitpicky = True` is a commit gate
of its own, run as `sphinx-build` directly.
"""

from __future__ import annotations

import re
import warnings
from pathlib import Path

import pytest

import designspace as ds

_ROOT = Path(__file__).resolve().parent.parent
_DOCS = _ROOT / "docs"
_EXAMPLES = _ROOT / "examples"
_DESIGN_NOTES = sorted((_DOCS / "design-notes").glob("*.md"))
_TUTORIALS = sorted(p for p in (_DOCS / "tutorials").glob("*.md") if p.stem != "index")
_EXAMPLE_SCRIPTS = sorted(_EXAMPLES.glob("*.py"))
# `_build` is gitignored output, not authored prose, and `conf.py` excludes it
# from the build for the same reason.
_DOC_SOURCES = sorted(p for p in _DOCS.rglob("*.md") if "_build" not in p.parts)

_SPEC = _ROOT / "API.md"
_ROOT_MARKDOWN = [
    _SPEC,
    _ROOT / "PLAN.md",
    _ROOT / "PROGRESS.md",
    _ROOT / "DECISIONS.md",
    _ROOT / "CLAUDE.md",
    _ROOT / "README.md",
]
_SOURCE = sorted((_ROOT / "src").rglob("*.py"))
_TESTS = sorted(p for p in (_ROOT / "tests").rglob("*.py") if "__pycache__" not in p.parts)
_CONFIG = [
    _ROOT / "pyproject.toml",
    _ROOT / ".github" / "workflows" / "ci.yml",
    _DOCS / "conf.py",
]

# Every tree the prose laws cover.
_PROSE_SOURCES = [
    *_DOC_SOURCES,
    *_EXAMPLE_SCRIPTS,
    _EXAMPLES / "README.md",
    *_ROOT_MARKDOWN,
    *_SOURCE,
    *_TESTS,
    *_CONFIG,
]

# Spelled as an escape so that this module satisfies the law it defines.
_EM_DASH = "\u2014"
# A decision-ledger entry number. Legal in DECISIONS.md, nowhere else.
_DECISION_CITATION = re.compile(r"\bD-\d+\b")
# A milestone number. Legal in PLAN.md and PROGRESS.md, whose subject it is.
_MILESTONE = re.compile(r"\bM\d+(?:\.\d+)?\b")
# A `tests/...py` path cited in the spec's "Enforced by" column.
_TEST_MODULE = re.compile(r"`(tests/[\w/]+\.py)`")
# A conformance-law row: name, statement, enforcing module.
_LAW_ROW = re.compile(r"^\| `([a-z0-9_]+)` \| .*? \| `(tests/[\w/]+\.py)` \|$", re.MULTILINE)
# A contents entry pointing at a heading of the same document.
_ANCHOR_LINK = re.compile(r"\]\(#([a-z0-9-]+)\)")
_HEADING = re.compile(r"^#{2,3} (.*)$", re.MULTILINE)
# Every heading `API.md` offers a citation, including its bold run-in form.
_ANY_HEADING = re.compile(r"^#{2,6} (.*)$", re.MULTILINE)
_RUN_IN_HEADING = re.compile(r"^(?:[-*]\s+)?\*\*(.+?)\.?\*\*", re.MULTILINE)
# A citation naming an API.md section, with its `>` continuations.
_SECTION_CITATION = re.compile(r'API\.md,\s*"([^"\n]+)"((?:\s*>\s*"[^"\n]+")*)')
_QUOTED = re.compile(r'"([^"\n]+)"')

# ```{code-cell}\n:tags: [...]\n<source>\n``` is myst-nb's executable block.
# Anchored at the fence so a mention in prose cannot match.
_CODE_CELL = re.compile(
    r"^```\{code-cell\}[^\n]*\n(?P<body>.*?)^```",
    re.MULTILINE | re.DOTALL,
)
# Directive options lead the body and are not Python.
_CELL_OPTION = re.compile(r"\A(?:^:[a-z-]+:.*$\n)+", re.MULTILINE)


def _slug(heading: str) -> str:
    """The anchor a markdown renderer derives from a heading."""
    return re.sub(r"\s+", "-", re.sub(r"[^\w\s-]", "", heading.strip().lower())).strip("-")


def _cite_lines(path: Path, pattern: re.Pattern[str]) -> list[str]:
    return [
        f"  line {i}: {line.strip()}"
        for i, line in enumerate(path.read_text().splitlines(), start=1)
        if pattern.search(line)
    ]


def test_reference_lists_every_export() -> None:
    """Every exported name appears in the API reference.

    Without this the reference silently stops covering the surface the
    moment something new is exported.
    """
    text = (_DOCS / "reference.md").read_text()
    missing = [
        name for name in ds.__all__ if name != "__version__" and f"designspace.{name}\n" not in text
    ]
    assert not missing, (
        f"{len(missing)} exported names are absent from docs/reference.md: "
        f"{', '.join(sorted(missing))}"
    )


def test_design_notes_exist() -> None:
    """The design-notes directory is not empty and is reachable from its index."""
    assert _DESIGN_NOTES, "docs/design-notes/ has no pages"
    index = (_DOCS / "design-notes" / "index.md").read_text()
    orphans = [p.stem for p in _DESIGN_NOTES if p.stem != "index" and p.stem not in index]
    assert not orphans, f"design notes missing from the toctree: {', '.join(orphans)}"


@pytest.mark.parametrize("page", _DESIGN_NOTES, ids=[p.stem for p in _DESIGN_NOTES])
def test_design_note_carries_doctests(page: Path) -> None:
    """Every design note except the index carries a runnable example.

    `--doctest-glob=*.md` runs them; this asserts there is something to run,
    so a page cannot quietly become prose-only while the gate reports green.
    """
    if page.stem == "index":
        pytest.skip("the index is a table of contents, not a design note")
    assert ">>>" in page.read_text(), (
        f"{page.name} carries no `>>>` example. A design note argues a "
        f"trade-off, and the argument is grounded in code that runs."
    )


def test_tutorial_pages_exist() -> None:
    """The tutorial directory is not empty and is reachable from its index."""
    assert _TUTORIALS, "docs/tutorials/ has no pages"
    index = (_DOCS / "tutorials" / "index.md").read_text()
    orphans = [p.stem for p in _TUTORIALS if p.stem not in index]
    assert not orphans, f"tutorial pages missing from the toctree: {', '.join(orphans)}"


@pytest.mark.parametrize("page", _TUTORIALS, ids=[p.stem for p in _TUTORIALS])
def test_tutorial_page_executes(page: Path) -> None:
    """Every `{code-cell}` on a tutorial page runs, in order, in one namespace.

    A tutorial's outputs are generated by myst-nb rather than written down, so
    nothing compares them against an expectation. What the pages assert instead
    is stated inline: cells carry `assert` statements for the claims their prose
    makes, and this law runs them on a plain `pytest -q`, in ~2s, naming the
    cell that raised. The site build runs the same cells for real.

    A page must open with `file_format: mystnb` front matter, or myst-nb parses
    it as ordinary markdown and silently renders the cells without ever running
    them.
    """
    text = page.read_text()
    assert text.startswith("---\nfile_format: mystnb\n---\n"), (
        f"{page.name} lacks `file_format: mystnb` front matter, so myst-nb will "
        f"render its code cells without executing them."
    )

    cells = [_CELL_OPTION.sub("", m.group("body")) for m in _CODE_CELL.finditer(text)]
    assert cells, f"{page.name} carries no `{{code-cell}}`; tutorial pages are executable"

    namespace: dict[str, object] = {}
    for number, source in enumerate(cells, start=1):
        try:
            # Pages demonstrate best-effort operations that warn by design.
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                exec(compile(source, f"{page.name}:cell{number}", "exec"), namespace)
        except Exception as exc:
            pytest.fail(
                f"{page.name} cell {number} raised {type(exc).__name__}: {exc}\n"
                f"--- cell source ---\n{source}"
            )


@pytest.mark.parametrize("path", _PROSE_SOURCES, ids=lambda p: str(p.relative_to(_ROOT)))
def test_no_em_dash_in_documentation_prose(path: Path) -> None:
    """Authored prose carries no U+2014.

    Objective, so it is gated. Register is not: second-person counts and
    antithesis counts are editorial judgment, and a threshold test over them
    would be brittle and would invite gaming.
    """
    lines = [
        f"  line {i}: {line.strip()}"
        for i, line in enumerate(path.read_text().splitlines(), start=1)
        if _EM_DASH in line
    ]
    assert not lines, f"{path.relative_to(_ROOT)} contains U+2014:\n" + "\n".join(lines)


@pytest.mark.parametrize(
    "path",
    [p for p in _PROSE_SOURCES if p.name != "DECISIONS.md"],
    ids=lambda p: str(p.relative_to(_ROOT)),
)
def test_no_decision_citations_outside_the_ledger(path: Path) -> None:
    """Only `DECISIONS.md` names a decision entry by number.

    An entry number written anywhere else may resolve to nothing a reader
    can open, an entry being deleted once its answer is folded into
    `API.md`. State the reason in words instead.
    """
    lines = _cite_lines(path, _DECISION_CITATION)
    assert not lines, f"{path.relative_to(_ROOT)} cites a decision entry by number:\n" + "\n".join(
        lines
    )


@pytest.mark.parametrize(
    "path",
    [p for p in _PROSE_SOURCES if p.name not in ("PLAN.md", "PROGRESS.md")],
    ids=lambda p: str(p.relative_to(_ROOT)),
)
def test_no_milestone_references_outside_the_plan(path: Path) -> None:
    """Milestone numbers appear only in `PLAN.md` and `PROGRESS.md`.

    Those two documents have milestones as their subject. Everywhere else a
    milestone number dates the text against a schedule the reader cannot see.
    """
    lines = _cite_lines(path, _MILESTONE)
    assert not lines, f"{path.relative_to(_ROOT)} references a milestone:\n" + "\n".join(lines)


def test_spec_cites_test_modules_that_exist() -> None:
    """Every test module named in the spec's conformance laws exists."""
    cited = sorted(set(_TEST_MODULE.findall(_SPEC.read_text())))
    assert cited, "API.md's conformance laws name no test module"
    missing = [name for name in cited if not (_ROOT / name).is_file()]
    assert not missing, f"API.md names test modules that do not exist: {', '.join(missing)}"


def test_spec_contents_links_resolve() -> None:
    """Every entry in the spec's contents list points at one of its headings."""
    text = _SPEC.read_text()
    headings = {_slug(h) for h in _HEADING.findall(text)}
    broken = sorted({a for a in _ANCHOR_LINK.findall(text) if a not in headings})
    assert not broken, f"API.md contents entries point at no heading: {', '.join(broken)}"


def _spec_headings() -> set[str]:
    """Every `API.md` heading a citation may name, run-in headings included."""
    text = _SPEC.read_text()
    return {h.strip() for h in _ANY_HEADING.findall(text)} | {
        h.strip() for h in _RUN_IN_HEADING.findall(text)
    }


@pytest.mark.parametrize("path", [*_SOURCE, *_TESTS], ids=lambda p: str(p.relative_to(_ROOT)))
def test_api_section_citations_resolve(path: Path) -> None:
    """Every `API.md` section a module cites is a heading of `API.md`.

    The citation form is a parenthesized `API.md` followed by a
    comma and the quoted section name, optionally continued with `>` and a
    quoted subsection name. A quotation of the spec's prose is not a
    citation and is not matched.

    Lines are joined before matching, so that a citation wrapping across a
    line break is checked like any other. That is what a line-by-line sweep
    misses, and it is how six stale section names survived the rename that
    introduced them.
    """
    joined = re.sub(r"\n\s*#?\s*", " ", path.read_text())
    cited: set[str] = set()
    for match in _SECTION_CITATION.finditer(joined):
        cited.add(match.group(1))
        cited.update(_QUOTED.findall(match.group(2)))
    unresolved = sorted(cited - _spec_headings())
    assert not unresolved, (
        f"{path.relative_to(_ROOT)} cites API.md sections that do not exist: "
        f"{', '.join(repr(name) for name in unresolved)}"
    )


def test_every_law_names_itself_in_its_own_module() -> None:
    """Every conformance law appears in the module its spec row assigns it.

    API.md's *Enforced by* column points from a law to a test module. This
    is the other direction: the module names the law, so that a law whose
    tests move, or whose name changes, cannot leave the column pointing at a
    module that no longer enforces it.
    """
    rows = _LAW_ROW.findall(_SPEC.read_text())
    assert rows, "API.md's conformance laws parse to no rows"
    missing = [
        f"{law} (expected in {module})"
        for law, module in rows
        if law not in (_ROOT / module).read_text()
    ]
    assert not missing, (
        f"{len(missing)} of {len(rows)} conformance laws are not named in the "
        f"module API.md assigns them:\n  " + "\n  ".join(missing)
    )
