"""designspace: declarative algorithm design spaces.

Public surface grows strictly with implemented milestones; see
PLAN.md. Nothing speculative is exported.
"""

from designspace.build import (
    BoolParamExpr,
    CategoricalParamExpr,
    ChoiceParamExpr,
    CodeParamExpr,
    CustomParamExpr,
    FreshParamExpr,
    IntegerParamExpr,
    ListParamExpr,
    OrdinalParamExpr,
    ParamExpr,
    PermutationParamExpr,
    RealParamExpr,
    Space,
    StructParamExpr,
    SubsetParamExpr,
    SymbolicParamExpr,
    TypedParamExpr,
    param,
    space,
)
from designspace.config import config_diff, destructure, flatten, payload, unflatten, variant
from designspace.custom import ParamType
from designspace.errors import DesignSpaceError, ResolutionError, SamplingError, SerializationError
from designspace.expr import ArithExpr, BoolExpr, Expr, all_, any_, count, value
from designspace.identity import config_hash
from designspace.ir import (
    BoolDomain,
    CategoricalDomain,
    Chart,
    ChoiceDomain,
    CodeDomain,
    CustomDomain,
    Domain,
    IntegerDomain,
    IntegerRemaining,
    ListDomain,
    Log,
    Logit,
    OrdinalDomain,
    ParamDef,
    ParamDiff,
    PartialEval,
    PermutationDomain,
    PermutationRemaining,
    Power,
    QuantizedSpec,
    RealDomain,
    RealRemaining,
    RemainingDomain,
    RepresentationCheck,
    RepresentationCheckFailure,
    StructDomain,
    SubsetDomain,
    SubsetRemaining,
    SubspaceInfo,
    SymbolicDomain,
    ValueRemaining,
)
from designspace.meta import param_from_def, space_from_ir
from designspace.program import FloatLiteral, IntLiteral, Primitive, Signature
from designspace.represent import Encoding, EncodingRule, Representation

__version__ = "0.0.0"

__all__ = [
    "ArithExpr",
    "BoolDomain",
    "BoolExpr",
    "BoolParamExpr",
    "CategoricalDomain",
    "CategoricalParamExpr",
    "Chart",
    "ChoiceDomain",
    "ChoiceParamExpr",
    "CodeDomain",
    "CodeParamExpr",
    "CustomDomain",
    "CustomParamExpr",
    "DesignSpaceError",
    "Domain",
    "Encoding",
    "EncodingRule",
    "Expr",
    "FloatLiteral",
    "FreshParamExpr",
    "IntLiteral",
    "IntegerDomain",
    "IntegerParamExpr",
    "IntegerRemaining",
    "ListDomain",
    "ListParamExpr",
    "Log",
    "Logit",
    "OrdinalDomain",
    "OrdinalParamExpr",
    "ParamDef",
    "ParamDiff",
    "ParamExpr",
    "ParamType",
    "PartialEval",
    "PermutationDomain",
    "PermutationParamExpr",
    "PermutationRemaining",
    "Power",
    "Primitive",
    "QuantizedSpec",
    "RealDomain",
    "RealParamExpr",
    "RealRemaining",
    "RemainingDomain",
    "Representation",
    "RepresentationCheck",
    "RepresentationCheckFailure",
    "ResolutionError",
    "SamplingError",
    "SerializationError",
    "Signature",
    "Space",
    "StructDomain",
    "StructParamExpr",
    "SubsetDomain",
    "SubsetParamExpr",
    "SubsetRemaining",
    "SubspaceInfo",
    "SymbolicDomain",
    "SymbolicParamExpr",
    "TypedParamExpr",
    "ValueRemaining",
    "__version__",
    "all_",
    "any_",
    "config_diff",
    "config_hash",
    "count",
    "destructure",
    "flatten",
    "param",
    "param_from_def",
    "payload",
    "space",
    "space_from_ir",
    "unflatten",
    "value",
    "variant",
]
