"""`wind_farm_grid` corpus fixture (PLAN.md corpus table,
added M3).

Exercises: subset + machine-generated pairwise forbids (static unrolling)
— one `.forbid()` per adjacent site pair, generated by a plain Python
loop over the declared item universe (no lift/instance-path machinery
needed; that's M4's per-element instantiation).
"""

from __future__ import annotations

import designspace as ds
from designspace import Space

SITES = tuple(f"site_{i}" for i in range(6))
ADJACENT_PAIRS = tuple((SITES[i], SITES[i + 1]) for i in range(len(SITES) - 1))


def build_space() -> Space:
    space = ds.space(
        ds.param("turbines").subset(SITES, min_size=1, max_size=4),
    )
    for a, b in ADJACENT_PAIRS:
        space = space.forbid(
            ds.param("turbines").contains(a) & ds.param("turbines").contains(b),
            tags=("spacing",),
        )
    return space
